### ISSUE TITLE
关于APP 常驻后台的一些疑问?

### ISSUE THREAD

**Issue by JamesLebron** [androidmalin/RengwuxianRxjava#1]
大神,你好.请问最近要做一个APP.需要长时间后台,发送定位信心到服务器.请问,有什么最优解的方法能长时间的保证APP在后台不被kill?
http://blog.csdn.net/mad1989/article/details/22492519 贴上此贴

**Comment by nukc** [comment]
@JamesLebron 同学，你可以看看这个 https://github.com/android-cn/android-discuss/issues/49

**Comment by androidmalin** [comment]
@JamesLebron 作为一个有理想的21世纪青年，这种做法，不提倡！

**Comment by androidmalin** [comment]
@JamesLebron [百万哥](https://github.com/liaohuqiu)</br> 给出了解答[请点击](http://m.weibo.cn/1503535883/3910838588548086/weixin?sourceType=weixin&from=1055095010&wm=2468_1001)

**Comment by androidmalin** [comment]
@JamesLebron 
[徐宜生](http://weibo.com/eclipsexu?from=feed&loc=nickname)</br> 给出了解答[请点击](http://m.weibo.cn/1904977584/3910841940698402/weixin?sourceType=weixin&from=1055095010&wm=2468_1001)

**Comment by JamesLebron** [comment]
@androidmalin  主要这个APP 是要求那种 犯人使用的,客户是司法局,有个需求,就是要实时定位,获取犯人的数据.观察犯人的位置.

**Comment by JamesLebron** [comment]
@nukc  谢谢大神,感觉很有用.

**Comment by xingrz** [comment]
获取定位信息不需要常驻后台
获取定位信息不需要常驻后台
获取定位信息不需要常驻后台

重要的事情说三遍

**Comment by liaohuqiu** [comment]
![image](https://cloud.githubusercontent.com/assets/4088573/11263164/b48b8e8e-8e3c-11e5-836d-03f2781aabb6.png)

**Comment by JamesLebron** [comment]
@xingrz  @liaohuqiu  好的.谢谢你们的意见.我和项目组讨论一下.

**Comment by JamesLebron** [comment]
@androidmalin   昨天刚刚问了你问题,晚上就看到了你的介绍.http://www.jcodecraeer.com/a/chengxusheji/chengxuyuan/2015/1119/3703.html
看到你的介绍,也想起了当初学Android 的样子,同样是看MARS 的视频,从JAVA4 Android 到后期的重制版视频,后期也看了一些黑马的培训视频.的确是这样,学的越深,学的越多,发现自己会的太少.期待以后你能发布更多的技术分享.我和其他读者都会一直支持你.             PS--还有机会加入你的 内测读者军么?

**Comment by androidmalin** [comment]
@JamesLebron 你留一个你的邮箱!

**Comment by JamesLebron** [comment]
@androidmalin  就我的QQ 邮箱:564757717@qq.com .谢谢大神.
